# docker-compose.yml
version: "3.8"

networks:
  dappnet:
    driver: bridge

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dappnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  ui:
    build: ./ui
    ports:
      - "5173:80"
    networks:
      - dappnet
    environment:
      - VITE_API_URL=http://api:3000
